--屏蔽城邦造奇观
DELETE FROM Civilization_BuildingClassOverrides
WHERE (CivilizationType = 'CIVILIZATION_BARBARIAN' OR CivilizationType = 'CIVILIZATION_MINOR') 
AND BuildingClassType != 'BUILDINGCLASS_PALACE'
AND BuildingClassType IN 
(SELECT Type FROM BuildingClasses WHERE Type = BuildingClassType AND (MaxPlayerInstances = 1 OR MaxGlobalInstances = 1));

INSERT INTO Civilization_BuildingClassOverrides(CivilizationType,BuildingClassType,BuildingType)
SELECT 'CIVILIZATION_BARBARIAN',Type,NULL FROM BuildingClasses
WHERE (MaxPlayerInstances = 1 OR MaxGlobalInstances = 1) AND Type != 'BUILDINGCLASS_PALACE' UNION ALL
SELECT 'CIVILIZATION_MINOR',Type,NULL FROM BuildingClasses
WHERE MaxPlayerInstances = 1 OR MaxGlobalInstances = 1 AND Type != 'BUILDINGCLASS_PALACE';


INSERT INTO Building_BuildingClassYieldChanges(BuildingType , BuildingClassType , YieldType , YieldChange)
--火电管理局增加发电站本地健康度
SELECT 'BUILDING_THERMAL_POWER_PLANNING_DEPARTMENT' , 'BUILDINGCLASS_COAL_PLANT' , 'YIELD_HEALTH',1 UNION ALL           --燃煤发电站
SELECT 'BUILDING_THERMAL_POWER_PLANNING_DEPARTMENT' , 'BUILDINGCLASS_COAL_PLANT_EXTEND', 'YIELD_HEALTH', 1 UNION ALL    --燃煤发电扩容机组
SELECT 'BUILDING_THERMAL_POWER_PLANNING_DEPARTMENT' , 'BUILDINGCLASS_OIL_PLANT' , 'YIELD_HEALTH',1 UNION ALL            --燃油发电站 
SELECT 'BUILDING_THERMAL_POWER_PLANNING_DEPARTMENT' , 'BUILDINGCLASS_GAS_PLANT', 'YIELD_HEALTH', 1 UNION ALL            --燃气发电站 

--工业规划局增加建筑本地健康度
SELECT 'BUILDING_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_FACTORY','YIELD_HEALTH',1 UNION ALL         --工厂
SELECT 'BUILDING_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_OIL_REFINERY','YIELD_HEALTH',1 UNION ALL    --石油精炼厂
SELECT 'BUILDING_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_STEEL_MILL','YIELD_HEALTH',1 UNION ALL      --增殖反应堆
SELECT 'BUILDING_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_MINING_COMPANY','YIELD_HEALTH',1 UNION ALL  --矿业公司
SELECT 'BUILDING_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_ORE_REFINERIES','YIELD_HEALTH',1 UNION ALL  --电冶金厂

--核电发展局增加核电站产能
SELECT 'BUILDING_NUCLEAR_POWER_MANAGEMENT_DEPARTMENT' , 'BUILDINGCLASS_NUCLEAR_PLANT','YIELD_PRODUCTION',3 UNION ALL        --核电站
SELECT 'BUILDING_NUCLEAR_POWER_MANAGEMENT_DEPARTMENT' , 'BUILDINGCLASS_NUCLEAR_PLANT_EXTEND','YIELD_PRODUCTION',3 UNION ALL --核电扩容机组
SELECT 'BUILDING_NUCLEAR_POWER_MANAGEMENT_DEPARTMENT' , 'BUILDINGCLASS_FUSION_PLANT','YIELD_PRODUCTION',3 UNION ALL         --核电扩容机组
SELECT 'BUILDING_NUCLEAR_POWER_MANAGEMENT_DEPARTMENT' , 'BUILDINGCLASS_THORIUM_REACTOR','YIELD_PRODUCTION',3;                --核电扩容机组


--政策增加建筑全局健康度
INSERT INTO Policy_BuildingClassYieldModifiers(PolicyType,BuildingClassType,YieldType,YieldMod)
SELECT 'POLICY_NUCLEAR_POWER_MANAGEMENT_DEPARTMENT' , 'BUILDINGCLASS_NUCLEAR_PLANT','YIELD_HEALTH',1 UNION ALL  --核电站
SELECT 'POLICY_NUCLEAR_POWER_MANAGEMENT_DEPARTMENT' , 'BUILDINGCLASS_NUCLEAR_PLANT_EXTEND','YIELD_HEALTH',1 UNION ALL --核电扩容机组

SELECT 'POLICY_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_FACTORY','YIELD_HEALTH',1 UNION ALL           --工厂
SELECT 'POLICY_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_OIL_REFINERY','YIELD_HEALTH',1 UNION ALL      --石油精炼厂
SELECT 'POLICY_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_STEEL_MILL','YIELD_HEALTH',1 UNION ALL        --增殖反应堆
SELECT 'POLICY_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_MINING_COMPANY','YIELD_HEALTH',1;             --矿业公司
--SELECT 'POLICY_INDUSTRIAL_PLANNING_DIVISION' , 'BUILDINGCLASS_ORE_REFINERIES','YIELD_HEALTH',1;             --电冶金厂